### ISSUE TITLE
Where is the OpenCL.tgz?

### ISSUE THREAD

**Issue by knight42** [emoon/extract-opencl-docs-dash#1]
Hi @emoon . I am using Zeal on ArchLinux and i am dying for the OpenCL offline documents. Would you please tell me where to find that archive? Thanks.

**Comment by emoon** [comment]
They are part of Dash and integrated in his data storage. https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/OpenCL

All data was downloaded from here (using wget -r)

http://www.khronos.org/registry/cl/sdk/1.1/docs/man/xhtml http://www.khronos.org/registry/cl/sdk/1.2/docs/man/xhtml http://www.khronos.org/registry/cl/sdk/2.0/docs/man/xhtml

And then I used the python script to generate the actual docset.

**Comment by knight42** [comment]
@emoon I figure out how to use it now. Thanks for your awesome script! :+1:

**Comment by emoon** [comment]
Sweet! The script has likely some rough edges as it was mainly made by trail'n'error so if you find some way ways to improve it please file a PR :)
